version: '3'

services:
  nibetg:
    image: telegraf
    hostname: nibetg
    container_name: nibetg
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Europe/Helsinki
      NIBE_HOST: "${NIBE_HOST}"
      INFLUXDB_HOST: "${INFLUXDB_HOST}"
      INFLUXDB_DB: "${INFLUXDB_DB}"
      INFLUXDB_USER: "${INFLUXDB_USER}"
      INFLUXDB_PASS: "${INFLUXDB_PASS}"
    network_mode: bridge
    restart: always

